version: 0.2

env:
  variables:
    REPO_NAME: "test-CI-CD"

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm i -g serverless
      - npm install
  pre_build:
    commands:
      - echo Starting unit tests at `date`
      #- npm test
      - echo Unit tests execution complete at `date`
  build:
    commands:
      - echo Building for ${ENV}...
      # - npm run start
      - aws configure set aws_access_key_id ${PROD_AWS_ACCOUNT_ACCESS_KEY} 
      - aws configure set aws_secret_access_key ${PROD_AWS_ACCOUNT_SECRET_KEY} 
      - aws configure set default.region ca-central-1 
      - aws configure set default.output json 
      # - npm run-script lint
      # - npm run test
      - mkdir -p target/${ENV}
      - sls deploy -s ${ENV} -r ca-central-1
  post_build:
    commands:
      - echo Copying artifacts to S3 at `date`
      - |
        if [ ${ENV} = "uat" ] || [ ${ENV} = "production" ]; then
          echo Copying artifacts with profile aws-prod
          aws s3 mb s3://${ARTIFACT_S3_BUCKET}
          aws s3 sync target/${ENV} "s3://${ARTIFACT_S3_BUCKET}" --cache-control "max-age=1"  --profile aws-prod
        else
          echo Copying artifacts with profile default
          aws s3 mb s3://${ARTIFACT_S3_BUCKET}
          aws s3 sync target/${ENV} "s3://${ARTIFACT_S3_BUCKET}" --cache-control "max-age=1" 
        fi
      - echo Copied artifacts to S3 at `date`

cache:
  paths:
    - "node_modules/**/*"

artifacts:
  type: zip
  files:
    - .aws/**/*
    - build-config/*
    - target/**/*
    - serverless.yml
